neo4j:
  image: neo4j:3.5
  ports:
    - "7474:7474"
    - "7473:7473"
    - "7687:7687"
  volumes:
    - ./neo4j/data:/data
    - ./neo4j/conf:/conf
    - ./neo4j/import:/import
    - ./neo4j/plugins:/plugins
  environment:
    NEO4J_AUTH: neo4j/password
    NEO4J_apoc_export_file_enabled: "true"
    NEO4J_apoc_import_file_enabled: "true"
    NEO4J_apoc_import_file_use__neo4j__config: "true"
    NEO4J_dbms_security_procedures_unrestricted: "apoc.\\*"
    
    
    
  